[build]
command = "yarn run build"
environment = { NODE_VERSION = "18.12.0" }
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200